### PR TITLE
Update link for IBM Spectrum Scale CSI Driver & Add snapshot support

### PR DESCRIPTION
**Pull request by Jainbrt**
1. Update document reference link for IBM Spectrum Scale CSI Driver entry
2. Add snapshot support with new CSI 2.2.0 release (ref : https://github.com/IBM/ibm-spectrum-scale-csi/releases/tag/v2.2.0)

### CODE REVIEW

**Comment by Jainbrt** [comment]
I signed it

**Comment by xing-yang** [comment]
The change looks good.

CLA issue needs to be resolved.

**Comment by Jainbrt** [comment]
Thanks @xing-yang , I have already successfully signed CLA.

**Comment by Jainbrt** [comment]
@xing-yang could you please review & approve this PR ?

**Pull request merged**
