### PR TITLE
Update JuiceFS supported access modes

### PR DESCRIPTION
**Pull request by xiaogaozi**

### CODE REVIEW

**Comment by xing-yang** [comment]
This PR touches many drivers. Can you limit the changes only to JuiceFS driver?

**Comment by xiaogaozi** [comment]
@xing-yang No problem, I'll update this PR later.

**Comment by xiaogaozi** [comment]
@xing-yang Hi, I've updated the PR, the changes other than JuiceFS only involve removing the space character at the end of each line, no changes to the content.

**Comment by xing-yang** [comment]
@xiaogaozi Please remove the changes to other drivers, even if it only involves spaces.

**Comment by xiaogaozi** [comment]
@xing-yang Thanks for the feedback, I'll update this PR later.

**Comment by xiaogaozi** [comment]
@xing-yang Please review again

**Review by saad-ali — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
