### PR TITLE
Remove unnecessary variable in book/src/_book/example/csi-setup.yaml 

### LINKED ISSUE #68: simplify deployments: avoid unnecessary env vars
Setting `--csi-address=$(CSI_ADDRESS)` is unnecessarily complex. The extra env variable isn't needed.

### PR DESCRIPTION
**Pull request by vinli-cn**
Modify book/src/_book/example/csi-setup.yaml
fix #68

### CODE REVIEW

**Comment by vinli-cn** [comment]
@saad-ali @Ipabon

Could you please help review this PR? thanks!

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by pohly** [comment]
/assign @xing-yang 

For approval.

**Pull request merged**
