### PR TITLE
Update snapshot-restore-feature.md

### PR DESCRIPTION
**Pull request by mcred**
Fixes a minor typo that affected the copy/paste code for Create a PVC from a VolumeSnapshot

### CODE REVIEW

**Comment by mcred** [comment]
"I signed it"

**Comment by xing-yang** [comment]
@mcred It still says you need CLA.  Maybe you need to reach out to Linux Help desk.

**Comment by mcred** [comment]
@xing-yang Thanks! Just opened a ticket.

**Pull request merged**
