### PR TITLE
add YanRong CSI driver to production drivers list

### PR DESCRIPTION
**Pull request by wpf710**

### CODE REVIEW

**Comment by wpf710** [comment]
I signed it

**Comment by msau42** [comment]
@saad-ali will be refactoring the drivers table to add additional information about each driver.  Can you also answer these questions?

* Which of the following (optional) features does your driver support:
  
  * dynamic provisioning
  * online resize or offline resize
  * block
  * snapshot
* Which AccessModes does your driver support?
* Are the volume supported by your driver: "Remote Persistent" "Local Persistent" or "Local Ephemeral"?

**Comment by wpf710** [comment]
> 
> 
> @saad-ali will be refactoring the drivers table to add additional information about each driver. Can you also answer these questions?
> 
>     * Which of the following (optional) features does your driver support:
>       
>       * dynamic provisioning
     it's dynamic provisioning
>       * online resize or offline resize
     our storage backend support online resize, but K8S v1.13 does not support resize well (as far as I know)
>       * block
         File Storage
>       * snapshot
         Not yet
> 
>     * Which AccessModes does your driver support?
         ReadWriteMany
> 
>     * Are the volume supported by your driver: "Remote Persistent" "Local Persistent" or "Local Ephemeral"?
         Sorry , I did not get your point.  You can treat it as distributed file storage, but it's high performance.

**Comment by wpf710** [comment]
@msau42

**Comment by msau42** [comment]
Hi @wpf710.

We're rewriting our drivers page to provide more information about each driver.  Is there a page to user documentation on how to use your CSI plugin that we can link to?  With examples for StorageClass, PVC, etc? 

We want to make sure that all the CSI drivers listed on this page are able to provide the basic information for Kubernetes users.

**Comment by saad-ali** [comment]
Ping @wpf710 could you please provide a link to a documentation page for your CSI driver?

**Comment by saad-ali** [comment]
Also what is the CSI Driver Name for your driver? For example, Amazon EBS driver's CSI driver name is `efs.csi.aws.com`.

**Pull request merged**
