### PR TITLE
add LINSTOR to the list of csi drivers

### PR DESCRIPTION
**Pull request by haySwim**

### CODE REVIEW

**Comment by msau42** [comment]
Thanks for the pr!

@saad-ali  will be refactoring the drivers table to add additional information about each driver. Can you also answer these questions?

* Which of the following (optional) features does your driver support:
  
  * dynamic provisioning
  * online resize or offline resize
  * block
  * snapshot
* Which AccessModes does your driver support?
* Are the volume supported by your driver: "Remote Persistent" "Local Persistent" or "Local Ephemeral"?

**Comment by haySwim** [comment]
> Thanks for the pr!
> 
> @saad-ali will be refactoring the drivers table to add additional information about each driver. Can you also answer these questions?
> 
>     * Which of the following (optional) features does your driver support:
>       
>       * dynamic provisioning
Check
>       * online resize or offline resize
Planned
>       * block
Planned
>       * snapshot
Planned
> 
>     * Which AccessModes does your driver support?
SINGLE_NODE_WRITER 
> 
>     * Are the volume supported by your driver: "Remote Persistent" "Local Persistent" or "Local Ephemeral"?

Remote Persistent and Local Persistent

**Comment by msau42** [comment]
Cool thanks!

/lgtm
/approve

**Pull request merged**
