### PR TITLE
Updating CSI RBD driver version

### PR DESCRIPTION
**Pull request by sbezverk**
New CSI RBD driver has been posted, updating the doc for new version.

### CODE REVIEW

**Comment by sbezverk** [comment]
@lpabon PTAL

**Comment by lpabon** [comment]
Do you mind generating the docs using [mdbook](https://github.com/kubernetes-csi/docs#kubernetes-csi-documentation).

**Comment by sbezverk** [comment]
@lpabon of course not, I just need to learn how to do it ;)

**Comment by sbezverk** [comment]
@lpabon done..

**Pull request merged**
