### PR TITLE
Added link to "Understanding CSI" medium document

### PR DESCRIPTION
**Pull request by maniankara**
This gives a high level overview and is a good prerequisite to start implementing CSI

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @maniankara isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by maniankara** [comment]
@thelinuxfoundation Alright, Now I have signed the CLA. Please re-check :)

**Comment by lpabon** [comment]
Looks good, but could you run `mdbook build` as shown [here](https://github.com/kubernetes-csi/docs#kubernetes-csi-documentation) to generate the pages?

**Comment by maniankara** [comment]
This is a duplicate of https://github.com/kubernetes-csi/docs/pull/44. Can be deleted.

**Pull request closed without merging**
