### PR TITLE
Update topology.md

### LINKED ISSUE #474: Typo: VOLUME_ACCESSIBILITY_CONTRAINTS should be VOLUME_ACCESSIBILITY_CONTSRAINTS
Locate at /docs/blob/master/book/src/topology.md

### PR DESCRIPTION
**Pull request by anooptp**
Fixes #474

### CODE REVIEW

**Comment by anooptp** [comment]
```release-note
Fixes #474 

Updated the word from VOLUME_ACCESSIBILITY_CONTRAINTS to VOLUME_ACCESSIBILITY_CONSTRAINTS 

```

**Comment by xing-yang** [comment]
Please fix the release note.  You can remove the "changes made".

**Comment by anooptp** [comment]
> Please fix the release note. You can remove the "changes made".

@xing-yang Thank you for your feedback.

**Comment by anooptp** [comment]
I have updated the release notes by removing the "changes made".

**Comment by anooptp** [comment]
/release-note-edit ``` Fixes #474 . Updated the word from VOLUME_ACCESSIBILITY_CONTRAINTS to VOLUME_ACCESSIBILITY_CONSTRAINTS  ```

**Comment by anooptp** [comment]
Opened a new PR #474 
Hence closing this.

**Pull request closed without merging**
