### PR TITLE
Fix EFS dynamic provisioning

### PR DESCRIPTION
**Pull request by ayrat555**
EFS supports dynamic provision from the version 1.2

-
https://aws.amazon.com/blogs/containers/introducing-efs-csi-dynamic-provisioning/
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/CHANGELOG-1.x.md#v12

### CODE REVIEW

**Comment by xing-yang** [comment]
Your PR made changes to multiple CSI drivers.  Can you please rebase so that only your driver is updated?

**Comment by ayrat555** [comment]
@xing-yang done!

**Comment by ayrat555** [comment]
@xing-yang it seems the automation is broken? the pr is not getting merged

**Review by xing-yang — APPROVED** [review]

**Pull request merged**
