### PR TITLE
Add Synology NAS driver to the list of drivers

### PR DESCRIPTION
**Pull request by jparklab**
I added to the list of sample drivers instead of production since I do not work for Synology and do not intend to support this driver for a production use.
I have been using this driver for my home lab.

### CODE REVIEW

**Comment by jparklab** [comment]
I finished the CLA signature.

**Comment by saad-ali** [comment]
Can you change the description from:

`A Container Storage Interface Driver for Synology NAS.` to `An unofficial (and unsupported) Container Storage Interface Driver for Synology NAS.`

**Comment by jparklab** [comment]
Good point, I updated the description

**Pull request merged**
