### PR TITLE
Update drivers.md - IBM Block storage driver 1.12.0 supports RWX, no more support for A9000

### PR DESCRIPTION
**Pull request by csiblock**

### CODE REVIEW

**Comment by csiblock** [comment]
/release-note-edit "IBM Block storage driver 1.12.0 supports RWX, no more support for A9000"

**Comment by csiblock** [comment]
@lpabon please review and approve this PR

**Comment by csiblock** [comment]
thank you @xing-yang 

the pull / build task is failing due to "Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/"
how can we fix this?

**Comment by xing-yang** [comment]
@csiblock I'm not sure. I have not seen this error before.  You may need to try to submit a new PR.

**Comment by csiblock** [comment]
closing this PR, as new PR #608 created so that updated pull / build check be run properly, now that PR #607 is merged

**Pull request closed without merging**
